version: "3"
services:
  relay-server:
    build:
      context: ./relay-server
      dockerfile: Dockerfile-dev
    ports:
      - "8989:8989"
    container_name: relay-server
    volumes:
      - ./relay-server
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    container_name: frontend
    volumes:
      - ./app
  postgres:
    image: postgres:12.7
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
