const mutations = {
  ADD_PEER: "ADD_PEER",
  SET_PEERS: "SET_PEERS",
  SET_PEER_STREAM: "SET_PEER_STREAM",
  SET_ROOM_CODE: "SET_ROOM_CODE",
  SET_AUDIO_STREAM: "SET_AUDIO_STREAM",
  SET_VIDEO_STREAM: "SET_VIDEO_STREAM",
}

export { mutations }