const mutations = {
  ADD_PEER: "ADD_PEER",
  DEAFEN_PEERS: "DEAFEN",
  SET_PEERS: "SET_PEERS",
  SET_PEER_STREAM: "SET_PEER_STREAM",
  SET_ROOM_CODE: "SET_ROOM_CODE",
  SET_AUDIO_STREAM: "SET_AUDIO_STREAM",
  SET_VIDEO_STREAM: "SET_VIDEO_STREAM",
  SET_OUTPUT_DEVICE: "SET_OUTPUT_DEVICE",
  SET_ACTIVE_SCREEN_ID: "SET_ACTIVE_SCREEN_ID",
};

export { mutations };
